# Generated by Django 2.1 on 2021-11-12 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='资源标题')),
                ('summary', models.TextField(default='资源摘要等同于网页description内容，请务必填写...', max_length=230, verbose_name='资源摘要')),
                ('body', models.TextField(verbose_name='资源内容')),
                ('img_link', models.CharField(default='/static/store/img/store.jpg', max_length=255, verbose_name='图片地址')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('deliver_type', models.CharField(choices=[('1', '自动发货'), ('2', '脚本发货'), ('3', '其他')], default='1', max_length=1, verbose_name='发货类型')),
                ('deliver_info', models.TextField(default='', verbose_name='发货信息')),
                ('slug', models.SlugField(unique=True)),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('amount', models.IntegerField(default=0, verbose_name='总量')),
                ('sales', models.IntegerField(default=0, verbose_name='销售量')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='提供者')),
                ('keywords', models.ManyToManyField(help_text='资源关键词，用来作为SEO中keywords，最好使用长尾词，3-4个足够', to='blog.Keyword', verbose_name='资源关键词')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(default='', max_length=200, verbose_name='备注')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('confirm_date', models.DateTimeField(auto_now=True, verbose_name='支付时间')),
                ('realPrice', models.IntegerField(default=0, verbose_name='实际支付金额')),
                ('uid', models.CharField(max_length=128, unique=True, verbose_name='订单编号')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('pay_type', models.CharField(choices=[('1', '微信'), ('2', '支付宝')], default='1', max_length=1, verbose_name='支付方式')),
                ('pay_url', models.CharField(default='', max_length=256, verbose_name='支付链接')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Item', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='购买者')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-create_date'],
            },
        ),
    ]
