# Generated by Django 2.2.20 on 2021-06-13 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackGroundCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='背景分类')),
            ],
            options={
                'verbose_name': '背景分类',
                'verbose_name_plural': '背景分类',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标题')),
                ('guonei', models.BooleanField(default=1, verbose_name='国内')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.IntegerField(default=1, help_text='分类显示顺序', verbose_name='顺序')),
            ],
            options={
                'verbose_name': '大分类',
                'verbose_name_plural': '大分类',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SmallCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='小分类')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.IntegerField(default=1, help_text='分类显示顺序', verbose_name='顺序')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Category', verbose_name='大分类')),
            ],
            options={
                'verbose_name': '小分类',
                'verbose_name_plural': '小分类',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='站点名')),
                ('desc', models.CharField(blank=True, max_length=100, verbose_name='描述')),
                ('image_url', models.ImageField(default='images/Site/default.png', upload_to='images/Site/%Y/%m/%d', verbose_name='图片')),
                ('true_url', models.URLField(blank=True, max_length=100, verbose_name='地址')),
                ('order', models.IntegerField(default=1, help_text='站点显示顺序', verbose_name='顺序')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('smallcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.SmallCategory', verbose_name='小分类')),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BackGround',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='背景名')),
                ('preview_url', models.ImageField(default='images/BackGround/background.png', upload_to='images/BackGround/preview/%Y/%m/%d', verbose_name='预览图')),
                ('image_url', models.ImageField(default='images/BackGround/background.png', upload_to='images/BackGround/image/%Y/%m/%d', verbose_name='真实图片')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('backgroundcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.BackGroundCategory', verbose_name='小分类')),
            ],
            options={
                'verbose_name': '背景',
                'verbose_name_plural': '背景',
                'ordering': ['id'],
            },
        ),
    ]
