# Generated by Django 2.2.20 on 2021-11-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211115_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否展示'),
        ),
    ]
