# Generated by Django 2.2.20 on 2022-01-15 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_carousel_is_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='资源标题')),
                ('summary', models.TextField(default='资源摘要等同于网页description内容，请务必填写...', max_length=230, verbose_name='资源摘要')),
                ('body', models.TextField(verbose_name='资源内容')),
                ('resource_type', models.CharField(choices=[('1', 'PDF'), ('2', 'ZIP')], default='1', max_length=1, verbose_name='资源格式')),
                ('img_link', models.CharField(default='/static/resource/img/resource.png', max_length=255, verbose_name='图片地址')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('download', models.PositiveIntegerField(default=0, verbose_name='下载量')),
                ('url', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='资源链接')),
                ('baidu_url', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='资源百度网盘链接')),
                ('baidu_code', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='资源百度网盘提取码')),
                ('slug', models.SlugField(unique=True)),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='提供者')),
                ('keywords', models.ManyToManyField(help_text='资源关键词，用来作为SEO中keywords，最好使用长尾词，3-4个足够', to='blog.Keyword', verbose_name='资源关键词')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
                'ordering': ['-create_date'],
            },
        ),
    ]
